version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "4000:3000" # localhost:4000 -> container:3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

# docker compose up --build -d

